version: "3"

services:
  populardishes:
    build: ./
    ports:
      - "3005:3005"
    depends_on:
      - "database"
    command: >
      bash -c "./wait-for-it.sh database:3306 && npm run seed-db && npm run start"
  database:
    image: mysql:5.7.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "yourpassword"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "dishes"
      MYSQL_USER: "student"
      MYSQL_PASSWORD: "student"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
